// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTObAmHiE1o4Om688GctLRdOn6fSOb9Qs',
    appId: '1:436536998730:web:f734e08672a2efe8be1fb3',
    messagingSenderId: '436536998730',
    projectId: 'cv-test-4c2a2',
    authDomain: 'cv-test-4c2a2.firebaseapp.com',
    storageBucket: 'cv-test-4c2a2.firebasestorage.app',
    measurementId: 'G-ZVDVGWNL8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgRMzHRtSao3hydr5_360ghLTj4WdZN50',
    appId: '1:436536998730:android:7005ec372dc7ce85be1fb3',
    messagingSenderId: '436536998730',
    projectId: 'cv-test-4c2a2',
    storageBucket: 'cv-test-4c2a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMAa54t0AB5nP9HSQtRoXfuXL33s-MP1o',
    appId: '1:436536998730:ios:be2c2751b7fd73b7be1fb3',
    messagingSenderId: '436536998730',
    projectId: 'cv-test-4c2a2',
    storageBucket: 'cv-test-4c2a2.firebasestorage.app',
    iosBundleId: 'com.example.cvtest.cvTest',
  );
}
